- hosts: all

  become: yes

  tasks:

    - name: Installer les dépendances

      apt:

        update_cache: yes

        name:

          - curl

          - wget

          - systemd
 
    - name: Copier l’application

      copy:

        src: app

        dest: /usr/local/bin/app

        mode: '0755'
 
    - name: Configurer systemd

      copy:

        content: |

          [Unit]

          Description=Go App

          After=network.target

          [Service]

          ExecStart=/usr/local/bin/app

          Restart=always

          User=nobody

          [Install]

          WantedBy=multi-user.target

        dest: /etc/systemd/system/app.service
 
    - name: Activer et démarrer l’application

      systemd:

        name: app

        enabled: yes

        state: started
 
